### ISSUE TITLE
Drone pull from private GCR registries

### ISSUE THREAD

**Issue by ljvmiranda921** [ljvmiranda921/ljvmiranda921.github.io#101]
1. Create a service account with Storage.Viewer (for pull), create a JSON key for that account
2. Perform Docker login based on [this step](https://medium.com/infrastructure-adventures/docker-registry-login-with-google-cloud-service-accounts-6bd528bed134)

```bash
docker login -u _json_key --password-stdin https://gcr.io < account.json
```

3. Go to Drone and add `$HOME/.docker/config.json` as a secret. Then, refer it to your `.drone.yml` as [such](https://docs.drone.io/user-guide/pipeline/secrets/#image-pull-secrets)

```yaml
kind: pipeline
name: default

steps:
- name: build
  image: testing/test-image
  commands:
  - go build
  - go test

image_pull_secrets:
- dockerconfigjson
```
